---
openapi: 3.0.3

info:
  title: The Maryland Test Facility Passive Presentation Attack Detection (P-PAD) System Interface
  description: This document describes an application programming interface for a PAD system in which
               the PAD subsystem is logically distinct from the Data Capture Subsystem.  This allows
               for what ISO/IEC 30107-1:2023 refers to as presentation attack detection "non-stimulated
               observation" of presentation attacks.  The standard and this document refer to these
               kinds of systems as "passive" PAD or P-PAD systems.
  version: 2.0.0
  contact:
    name: The MdTF
    url: https://mdtf.org
    email: rivtd@mdtf.org
  license:
    name: Copyright (c) 2022, The Maryland Test Facility

servers:
  - url: https://api.mdtf.org/
    variables:
      host:
        default: mdtf.org
      port:
        enum:
          - '8080'
        default: '8080'

tags:
  - name: Data Analysis 
  - name: Algorithm Information

paths:
  /v1/analyze-data-for-pad:
    post:
      summary: Analyze biometric capture data for a presentation attack.
      description: |
        Passive PAD systems receive data through this endpoint
      tags:
        - Data Analysis
      requestBody:
        $ref: '#/components/requestBodies/biometric_capture_data'
      responses:
        200:
          description: Successfully analyzed the provided sample for a presentation attack.
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        410:
          $ref: '#/components/responses/410'
        429:
          $ref: '#/components/responses/429'
        500:
          $ref: '#/components/responses/500'
  /v1/info:
    get:
      summary: Returns basic information for the algorithm.
      description: |
        This endpoint returns some basic information about the algorithm.
      tags:
        - Algorithm Information
      operationId: GetInfo
      responses:
        200:
          $ref: '#/components/responses/info_response'
        500:
          $ref: '#/components/responses/Error'
          
components:
  schemas:
    BiometricSample:
      type: string
      description: The captured biometric sample, encoded as a base64 string.  This can be an image, encoded as a PNG or JPEG
                   or a short (<15s) video, encoded as a MOV.
      example: iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAEElEQVR4nGJiYGAABAAA//8ADAADcZGLFwAAAABJRU5ErkJggg==
      x-nullable: false
    PADAnalysis:
      description: Data transfer object for presentation attack information.
      type: object
      required:
        - PADOutcome
        - PADScore
      properties:
        PADOutcome:
          description: Whether a presentation attack was determined to be detected (True) or not detected (False).
          type: boolean
          example: true
        PADScore:
          description: A score corresponding to the level of confidence that a presentation attack was detected ranging between 0 and 1.
          type: number
          format: double
          example: 0.8
        PADProperties:
          description: Key value pairs describing presentation attack properties and their relationship to the presentation attack outcome/score. 
            There are no strictly defined  properties. The inclusion of descriptive properties is encouraged to provide
            more context. (optional)
          type: array
          items:
            $ref: '#/components/schemas/PADProperty'
          example:
            - Property: EyesMoving
              Value: true
            - Property: MouthMoving
              Value: true
            - Property: PupilsResponsive
              Value: true
            - Property: NonconformantIlluminationDetected
              Value: true
            - Property: MoirePatternDetected
              Value: true
            - Property: ObsscurationDetected
              Value: true
    PADProperty:
      description: Key value pair object.
      type: object
      properties:
        Property:
          description: Name of the property.
          type: string
          example: EyesMoving
        Value:
          description: Value for the property.
          type: string
          example: true
    PADErrorResponse:
      description: Presentation attack error response object.
      type: object
      required:
        - error
      properties:
        error:
          description: Descriptive error string.
          type: string
   
    Error:
      type: object
      properties:
        Code:
          type: integer
          description: The error code.
        Message:
          type: string
          description: A description of the returned code.
        ErrorString:
          type: string
          description: A detailed description of the error that occurred.

  requestBodies:
    biometric_capture_data:
      description: Biometric capture data to be analyzed for evidence of a presentation attack.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BiometricSample'

  responses:
    pad_aalysis_response:
      description: The result of an analysis of a biometric sample for a presentation attack.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PADAnalysis'
    info_response:
      description: info response object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Info'
    400:
      description: The request is malformed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    429:
      description: Too many requests for the ongoing transaction.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    500:
      description: This capture failed because of a server side issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
