---
openapi: 3.0.3

info:
  title: The Maryland Test Facility Acquisition System Interface
  description: Application Programming Interface for sending acquisition records to the MdTF Backend.
  version: 2.0.0
  contact:
    name: The MdTF
    url: https://mdtf.org
    email: rally@mdtf.org
  license:
    name: Copyright (c) 2022, The Maryland Test Facility

servers:
  - url: http://api.mdtf.org/
    variables:
      host:
        default: ids.lab
      port:
        enum:
          - '8080'
        default: '8080'

tags:
  - name: Image Submission
    description: Endpoints for submitting images to an ongoing transaction.

components:
  schemas:
    FaceCapture:
      type: object
      required: [StationID, FaceImageData]
      properties:
        StationID:
          type: string
          description: The unique identifier for the station that the image was captured at.
          example: Station_A
          x-nullable: false
        FaceImageData:
          type: string
          description: The captured face image data in PNG format, encoded as a base64 string. The data string shall not exceed 1MB.
          example: iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAEElEQVR4nGJiYGAABAAA//8ADAADcZGLFwAAAABJRU5ErkJggg==
          x-nullable: false

    Error:
      type: object
      properties:
        Code:
          type: integer
          description: The error code.
        Message:
          type: string
          description: A description of the returned code.
        ErrorString:
          type: string
          description: A detailed description of the error that occurred.

  requestBodies:
    face_capture:
      description: Face image collected as part of a transaction.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FaceCapture'

  responses:
    400:
      description: The request is malformed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404:
      description: No ongoing transaction was found for the specified StationID.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    410:
      description: The test volunteer has exited the station and the transaction has ended.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    429:
      description: Too many requests for the ongoing transaction.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    500:
      description: This capture failed because of a server side issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

paths:
  /v1/face-captures:
    post:
      summary: Associate a face image capture with the ongoing transaction.
      description: |
        Acquisition System Providers may submit face image data through this endpoint. Submitted image captures will be
        stored and associated with the ongoing transaction. Multiple images may be submitted during a transaction.
      tags:
        - Image Submission
      requestBody:
        $ref: '#/components/requestBodies/face_capture'
      responses:
        200:
          description: Successfully associated the image capture with the ongoing transaction.
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        410:
          $ref: '#/components/responses/410'
        429:
          $ref: '#/components/responses/429'
        500:
          $ref: '#/components/responses/500'
