---
openapi: 3.1.0

info:
  title: The Maryland Test Facility Acquisition System Interface
  description: Application Programming Interface for sending acquisition records to the MdTF Backend.
  version: 2.1.0
  contact:
    name: The MdTF
    url: https://mdtf.org
    email: rally@mdtf.org
  license:
    name: Copyright (c) 2024, The Maryland Test Facility

servers:
  - url:
      http://idsl-blackops09.idslabs.net/acquisition
  - url:
      https://acquisition-demo.mdtf.org

tags:
  - name: Image Submission
    description: Endpoints for submitting images to an ongoing transaction.

components:
  schemas:
    Capture:
      type: object
      required: [StationID, Data]
      properties:
        StationID:
          type: string
          description: The unique identifier for the station that the image was captured at.
          examples:
            - Station_A
            - Station_B
            - Station_C
          x-nullable: false
        Data:
          type: string
          format: byte
          description: The raw bytes of the image data. The supported formats are jpeg and png. This data should be marshaled in this object as a base64 encoded string.
          examples:
            - "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAEElEQVR4nGJiYGAABAAA//8ADAADcZGLFwAAAABJRU5ErkJggg=="
          x-nullable: false

    Error:
      type: object
      required: [Code, Message, ErrorString]
      properties:
        Code:
          type: integer
          description: The error code.
        Message:
          type: string
          description: A description of the returned code.
        ErrorString:
          type: string
          description: A detailed description of the error that occurred.

  requestBodies:
    capture:
      description: Face image collected as part of a transaction.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Capture'

  responses:
    '400':
      description: The request is malformed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: No ongoing transaction was found for the specified StationID.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: This capture failed because of a server side issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

paths:
  /v1/capture:
    post:
      summary: Associate a capture with the ongoing transaction.
      description: |
        Acquisition system providers may submit image data through this endpoint. Submitted image captures will be
        stored and associated with the ongoing transaction. Multiple images may be submitted during a transaction.
      tags:
        - Image Submission
      operationId: Capture
      requestBody:
        $ref: '#/components/requestBodies/capture'
      responses:
        '200':
          description: Successfully associated the image capture with the ongoing transaction.
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
