---
openapi: 3.0.3

info:
  title: The Maryland Test Facility Acquisition System Interface
  description: Application Programming Interface for sending acquisition records to the MdTF Backend.
  version: 2.0.0
  contact:
    name: The MdTF
    url: https://mdtf.org
    email: rally@mdtf.org
  license:
    name: Copyright (c) 2022, The Maryland Test Facility
servers:
  - url: https://api.mdtf.org/
    variables:
      host:
        default: ids.lab
      port:
        enum:
          - '8080'
        default: '8080'
tags:
  - name: Image Submission
    description: Endpoints for submitting images to an ongoing transaction.
  - name: Video Submission
    description: Endpoints for submitting videos to an ongoing transaction.
components:
  schemas:
    FaceCapture:
      type: object
      required:
        - StationID
        - FaceImageData
      properties:
        StationID:
          description: The unique identifier for the station that the artifact was captured at.
          type: string
          example: Station_A
        FaceImageData:
          description: The captured face image data in PNG format, encoded as a base64 string. The data string shall not exceed 1MB.
          type: string
          format: byte
          example: iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAEElEQVR4nGJiYGAABAAA//8ADAADcZGLFwAAAABJRU5ErkJggg==
        PADResult:
          $ref: '#/components/schemas/PADResult'
    VideoCapture:
      type: object
      required:
        - StationID
        - VideoData
      properties:
        StationID:
          description: The unique identifier for the station that the artifact was captured at.
          type: string
          example: Station_A
        VideoData:
          description: base64 encoded bytes of the video data.
          type: string
          format: byte
        PADResult:
          $ref: '#/components/schemas/PADResult'
    PADResult:
      description: The result data from a PAD interaction
      type: object
      required:
        - outcome
        - score
        - properties
      properties:
        Outcome:
          description: The result of the interaction, whether a sample is bona-fide (true) or a presentation attack (false)
          type: boolean
        Score:
          description: The level of confidence that the sample is a presentation attack. If the score is 0.0, then there is 0% certainty the sample is a PA. If the score is a 1.0, then there is 100% certainty the sample is a PA.
          type: number
          format: double
        Properties:
          description: A list of key:value string pairs that provide further information or details about the response.
          type: array
          items:
            type: object
            properties:
              Property:
                type: string
              Value:
                type: string
    Error:
      type: object
      properties:
        Code:
          type: integer
          description: The error code.
        Message:
          type: string
          description: A description of the returned code.
        ErrorString:
          type: string
          description: A detailed description of the error that occurred.
  requestBodies:
    face_capture:
      description: Face image collected as part of a transaction.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FaceCapture'
  responses:
    400:
      description: The request is malformed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404:
      description: No ongoing transaction was found for the specified StationID.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    410:
      description: The test volunteer has exited the station and the transaction has ended.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    429:
      description: Too many requests for the ongoing transaction.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    500:
      description: This capture failed because of a server side issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
paths:
  /v1/face-captures:
    post:
      summary: Associate a face image capture with the ongoing transaction.
      description: |
        Acquisition system providers may submit face image data through this endpoint. Submitted image captures will be
        stored and associated with the ongoing transaction. Multiple images may be submitted during a transaction.
      tags:
        - Image Submission
      requestBody:
        $ref: '#/components/requestBodies/face_capture'
      responses:
        200:
          description: Successfully associated the image capture with the ongoing transaction.
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        410:
          $ref: '#/components/responses/410'
        429:
          $ref: '#/components/responses/429'
        500:
          $ref: '#/components/responses/500'
  /v1/video-captures:
    post:
      summary: Associate a video capture with the ongoing transaction.
      description: |
        Acquisition system providers may submit video data through this endpoint. Submitted video captures will be
        stored and associated with the ongoing transaction. Multiple images may be submitted during a transaction.
      operationId: AssociateVideoCaptures
      tags:
        - Video Submission
      requestBody:
        $ref: '#/components/requestBodies/face_capture'
      responses:
        200:
          description: Successfully associated the image capture with the ongoing transaction.
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        410:
          $ref: '#/components/responses/410'
        429:
          $ref: '#/components/responses/429'
        500:
          $ref: '#/components/responses/500'
