openapi: 3.0.3
info:
  title: MdTF Media Acquisition API
  version: 3.0.0
  description: |
    API for submitting media (images, video, audio) with support for multiple modalities.
    Each media type and modality combination has its own endpoint.
    Clients must use a single POST request with multipart/form-data to submit both the media file and its metadata.

servers:
  - url: https://api.mdtf.org

components:
  schemas:
    MediaFormat:
      type: string
      enum: [jpeg, png, wsq, bmp, mp4, mov, wav, mp3, flac]

    ImageFormat:
      type: string
      enum: [jpeg, png, wsq, bmp]

    VideoFormat:
      type: string
      enum: [mp4, mov]

    AudioFormat:
      type: string
      enum: [wav, mp3, flac]

    Modality:
      type: string
      enum: [Palm, Face, Iris, Finger, Voice]

    ImageModality:
      type: string
      enum: [Palm, Face, Iris, Finger]

    VideoModality:
      type: string
      enum: [Face]

    AudioModality:
      type: string
      enum: [Voice]

    BiometricImageType:
      type: string
      description: The allowed string names for biometric image types.
      enum:
        - Unknown
        - UnknownFinger
        - RightThumb
        - RightIndexFinger
        - RightMiddleFinger
        - RightRingFinger
        - RightLittleFinger
        - RightTwo
        - LeftThumb
        - LeftIndexFinger
        - LeftMiddleFinger
        - LeftRingFinger
        - LeftLittleFinger
        - FlatRightThumb
        - FlatLeftThumb
        - FlatRightFourFingers
        - FlatLeftFourFingers
        - FlatLeftAndRightThumbs
        - RightExtraDigit
        - LeftExtraDigit
        - UnknownFrictionRidge
        - EjiOrTip
        - Iris
        - RightIris
        - LeftIris
        - Face
        - RightPalm
        - LeftPalm
        - RightIndexAndMiddle
        - RolledRightThumb
        - RolledRightIndexFinger
        - RolledRightMiddleFinger
        - RolledRightRingFinger
        - RolledRightLittleFinger
        - RolledLeftThumb
        - RolledLeftIndexFinger
        - RolledLeftMiddleFinger
        - RolledLeftRingFinger
        - RolledLeftLittleFinger
        - RolledLeftExtraDigit
        - RolledRightExtraDigit
        - RightRingAndLittle
        - LeftIndexAndMiddle
        - LeftRingAndLittle

    UploadMetadataBase:
      type: object
      required: [StationID, Timestamp]
      properties:
        StationID:
          type: string
        Timestamp:
          type: string
          format: date-time
        Metadata:
          type: object
          additionalProperties: true
          example:
            - lighting: normal
            - sleepy: yes

    UploadImageMetadata:
      allOf:
        - $ref: '#/components/schemas/UploadMetadataBase'
        - type: object
          required: [Format, Modality]
          properties:
            Format:
              $ref: '#/components/schemas/ImageFormat'
            ImageType:
              $ref: '#/components/schemas/BiometricImageType'
            Modality:
              $ref: '#/components/schemas/ImageModality'

    UploadVideoMetadata:
      allOf:
        - $ref: '#/components/schemas/UploadMetadataBase'
        - type: object
          required: [Format, Modality]
          properties:
            Format:
              $ref: '#/components/schemas/VideoFormat'
            Modality:
              $ref: '#/components/schemas/VideoModality'

    UploadAudioMetadata:
      allOf:
        - $ref: '#/components/schemas/UploadMetadataBase'
        - type: object
          required: [Format, Modality]
          properties:
            Format:
              $ref: '#/components/schemas/AudioFormat'
            Modality:
              $ref: '#/components/schemas/AudioModality'

  requestBodies:
    MultipartUploadImage:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            required: [file, metadata]
            properties:
              file:
                type: string
                format: binary
              metadata:
                $ref: '#/components/schemas/UploadImageMetadata'

    MultipartUploadVideo:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            required: [file, metadata]
            properties:
              file:
                type: string
                format: binary
              metadata:
                $ref: '#/components/schemas/UploadVideoMetadata'

    MultipartUploadAudio:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            required: [file, metadata]
            properties:
              file:
                type: string
                format: binary
              metadata:
                $ref: '#/components/schemas/UploadAudioMetadata'

paths:
  /image/face:
    post:
      summary: Upload face image
      requestBody:
        $ref: '#/components/requestBodies/MultipartUploadImage'
      responses:
        '200':
          description: Upload successful
        '400':
          description: Malformed request or metadata

  /image/iris:
    post:
      summary: Upload iris image (left/right)
      requestBody:
        $ref: '#/components/requestBodies/MultipartUploadImage'
      responses:
        '200':
          description: Upload successful
        '400':
          description: Malformed request or metadata

  /image/finger:
    post:
      summary: Upload fingerprint image
      requestBody:
        $ref: '#/components/requestBodies/MultipartUploadImage'
      responses:
        '200':
          description: Upload successful
        '400':
          description: Malformed request or metadata

  /image/palm:
    post:
      summary: Upload palm image
      requestBody:
        $ref: '#/components/requestBodies/MultipartUploadImage'
      responses:
        '200':
          description: Upload successful
        '400':
          description: Malformed request or metadata

  /video/face:
    post:
      summary: Upload face video
      requestBody:
        $ref: '#/components/requestBodies/MultipartUploadVideo'
      responses:
        '200':
          description: Upload successful
        '400':
          description: Malformed request or metadata

  /audio/voice:
    post:
      summary: Upload voice audio
      requestBody:
        $ref: '#/components/requestBodies/MultipartUploadAudio'
      responses:
        '200':
          description: Upload successful
        '400':
          description: Malformed request or metadata
