---
openapi: 3.0.3

info:
  title: The Maryland Test Facility Matching System Interface
  description: Application Programming Interface for receiving matching system requests from the MdTF Backend.
  version: 1.1.1
  contact:
    name: The MdTF
    url: https://mdtf.org
    email: rally@mdtf.org
  license:
    name: IDSL API License
    url: https://raw.githubusercontent.com/TheMdTF/mdtf-public/master/LICENSE.md

servers:
  - url: http://localhost:8080/

tags:
  - name: Biometric Operations
  - name: Algorithm Information

components:

  schemas:

    Image:
      type: object
      description: |
        Data transfer object for an image.
      properties:
        ImageData:
          type: string
          description: The captured image data in PNG or JPG format, encoded as a base64 string.
          example: iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAEElEQVR4nGJiYGAABAAA//8ADAADcZGLFwAAAABJRU5ErkJggg==
          x-nullable: false
      required:
        - ImageData

    Template:
      type: object
      description: |
        Data transfer object for a template.
      properties:
        Template:
          description: The template data, encoded as a base64 string.  The data string shall not exceed 1 MB.
          type: string
          example: dGhpcyBzZW50ZW5jZSBpcyBhbiBleGFtcGxlIHRlbXBsYXRlLi4K
          x-nullable: false
      required:
        - Template

    Comparison:
      type: object
      description: |
        A similarity score for a single (1:1) template comparison operation.
        Scores should be, but are not required to be, consistent (unchanged)
        for existing templates if additional templates are added, that is, each
        score for a template should be independent of the presence or absence
        of other templates in the target set.
      properties:
        Score:
          type: number
          format: float
          description: A similarity score, as produced by the algorithm.
          example: 8734
          x-nullable: false
      required:
        - Score

    CompareListRequest:
      description: A single probe template object and a list of target templates that it will be compared to.
      type: object
      properties:
        ProbeTemplate:
          $ref: '#/components/schemas/Template'
        TargetTemplateList:
          type: array
          items:
            $ref: '#/components/schemas/Template'
          x-nullable: false
      required:
        - ProbeTemplate
        - TargetTemplateList

    Info:
      type: object
      description: Basic information describing the algorithm.
      properties:
        AlgorithmName:
          type: string
          description: Name of algorithm.
          example: AlwaysTrue
        AlgorithmVersion:
          type: string
          description: Algorithm version identifier.
          example: 1.0.1
        AlgorithmModality:
          type: string
          enum:
            - Face
            - Finger
            - Iris
          description: A string enum describing the type of biometric images the algorithm is meant to process.
        CompanyName:
          type: string
          description: Name of the Company which produced the algorithm.
          example: MdTF
        TechnicalContactEmail:
          type: string
          description: |
            The email address of an engineer or other technical resource to contact in the event of
            an error running your service.
          example: john@mdtf.org
        RecommendedCPUs:
          type: number
          format: float
          description: The recommended allocation of CPUs for the deployed docker container.
          example: .5
          maximum: 8
        RecommendedMem:
          type: integer
          description: The recommended allocation of memory (MB) for the deployed docker container.
          example: 512
          maximum: 8192
        Test:
          description: A string enum describing which collection event the algorithm is being submitted for.
          type: string
          enum:
            - MDTF_2022_RALLY
        Thresholds:
          description: |
            A map of preset False Match Rates (FMR) to vendor-provided threshold values. Score values returned from calls to
            v1/compare-list indicate a matching determination by the algorithm if they are greater than the provided threshold
            value at the respective FMR.
            Note that threshold values are floats stored as strings and cannot exceed a length of 10 characters.
            There are 5 required thresholds.
          maxProperties: 5
          type: object
          properties:
            1:500:
              type: string
              maxLength: 10
            1:1e3:
              type: string
              maxLength: 10
            1:1e4:
              type: string
              maxLength: 10
            1:1e5:
              type: string
              maxLength: 10
            1:1e6:
              type: string
              maxLength: 10
          required:
            - 1:500
            - 1:1e3
            - 1:1e4
            - 1:1e5
            - 1:1e6
          example:
            1:500: '7543'
            1:1e3: '8730'
            1:1e4: '9321'
            1:1e5: '9863'
            1:1e6: '9972'
      required:
        - AlgorithmName
        - AlgorithmVersion
        - AlgorithmModality
        - CompanyName
        - TechnicalContactEmail
        - RecommendedCPUs
        - RecommendedMem
        - Test
        - Thresholds

    RequestError:
      type: string
      description: |
        Relevant and concise diagnostic information in the event of a client side error (e.g. malformed requests, or invalid
        image encoding).
      example: Unable to decode image data as a PNG or JPG.

    ServerError:
      type: string
      description: |
        Relevant and concise diagnostic information in the event of a server side error
        (e.g. invalid license, or failure to generate a template).
      example: The internal license has expired.

  requestBodies:
    image:
      description: |
        The biometric image that is being submitted for feature extraction.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Image'

    compare_list_request:
      description: A single template object and a list of templates that it will be compared to.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CompareListRequest'

  responses:

    infoResponse:
      description: info response object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Info'

    templateResponse:
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Template'

    compareListResponse:
      description: Successful Response
      content:
        application/json:
          schema:
            type: array
            description: |
              An array of comparison results. This list MUST contain the same number of elements AND be in
              the same order as the provided list of templates.
            items:
              $ref: '#/components/schemas/Comparison'

    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerError'

paths:

  /v1/create-template:
    post:
      summary: Generate a template from the provided biometric image.
      description: |
        This endpoint accepts a base64 encoded PNG or JPG and attempts to perform a feature extraction operation producing a
        single template.
      tags:
        - Biometric Operations
      operationId: GenerateTemplate
      requestBody:
        $ref: '#/components/requestBodies/image'
      responses:
        200:
          $ref: '#/components/responses/templateResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalServerError'

  /v1/compare-list:
    post:
      summary: Compare a single probe template to a list of target templates.
      description: |
        This endpoint accepts a template and a list of templates. It compares the probe template to every target template in the
        provided list. The result is a list of Comparison objects that holds a similarity score for each comparison. 
        The returned list of comparisons MUST contain the same number of elements AND be in the same order as the provided list
        of templates.  Up to 10,000 target templates should be supported in the list of templates.
      tags:
        - Biometric Operations
      operationId: CompareTemplateList
      requestBody:
        $ref: '#/components/requestBodies/compare_list_request'
      responses:
        200:
          $ref: '#/components/responses/compareListResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalServerError'

  /v1/info:
    get:
      summary: Returns basic information for the algorithm.
      description: |
        This endpoint returns some basic information about the algorithm.
      tags:
        - Algorithm Information
      operationId: GetInfo
      responses:
        200:
          $ref: '#/components/responses/infoResponse'
        500:
          $ref: '#/components/responses/InternalServerError'
