---
openapi: 3.0.3

info:
  title: The Maryland Test Facility Presentation Attack Detection Analysis System Interface
  description: Application Programming Interface for analyzing a sample for a presentation attack and reporting that information to the MdTF Backend.
  version: 2.0.0
  contact:
    name: The MdTF
    url: https://mdtf.org
    email: rivtd@mdtf.org
  license:
    name: Copyright (c) 2022, The Maryland Test Facility

servers:
  - url: https://api.mdtf.org/
    variables:
      host:
        default: mdtf.org
      port:
        enum:
          - '8080'
        default: '8080'

tags:
  - name: PAD Analysis 
    description: Endpoints that analyze a sample for a presentation attack.

paths:
  /v1/analyze-pad:
    post:
      summary: Analyze a sample for a presentation attack.
      description: |
        PAD Analysis system providers will be provided samples through this endpoint.
      tags:
        - PAD Analysis
      requestBody:
        $ref: '#/components/requestBodies/image'
      responses:
        200:
          description: Successfully analyzed the provided sample for a presentation attack.
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        410:
          $ref: '#/components/responses/410'
        429:
          $ref: '#/components/responses/429'
        500:
          $ref: '#/components/responses/500'
          
components:
  schemas:
    Image:
      type: object
      description: |
        Data transfer object for an image.
      properties:
        ImageData:
          type: string
          format: byte
          description: The captured image data in PNG or JPG format, encoded as a base64 string.
          example: iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAEElEQVR4nGJiYGAABAAA//8ADAADcZGLFwAAAABJRU5ErkJggg==
          x-nullable: false
      required:
        - ImageData
    PADProperty:
      description: Key value pair object.
      type: object
      properties:
        Property:
          description: Name of the property.
          type: string
          example: EyesMoving
        Value:
          description: Value for the property.
          type: string
          example: true
    PADAnalysis:
      description: Data transfer object for the analysis of a sample for a presentation attack.
      type: object
      required:
        - PADOutcome
        - PADScore
      properties:
        PADOutcome:
          description: Whether a presentation attack was determined to be detected (True) or not detected (False).
          type: boolean
          example: true
        PADScore:
          description: A score corresponding to the level of confidence that a presentation attack was detected ranging between 0 and 1.
          type: number
          format: double
          example: 0.8
        PADProperties:
          description: Key value pairs describing presentation attack properties and their relationship to the presentation attack outcome/score. 
            There are no strictly defined  properties. The inclusion of descriptive properties is encouraged to provide
            more context. (optional)
          type: array
          items:
            $ref: '#/components/schemas/PADProperty'
          example:
            - Property: EyesMoving
              Value: true
            - Property: MouthMoving
              Value: true
            - Property: PupilsResponsive
              Value: true
            - Property: DifferentialReflectanceDetected
              Value: true
            - Property: MoirePatternDetected
              Value: true
    PADErrorResponse:
      description: Presentation attack error response object.
      type: object
      required:
        - error
      properties:
        error:
          description: Descriptive error string.
          type: string
   
    Error:
      type: object
      properties:
        Code:
          type: integer
          description: The error code.
        Message:
          type: string
          description: A description of the returned code.
        ErrorString:
          type: string
          description: A detailed description of the error that occurred.

  requestBodies:
    image:
      description: |
        The facial biometric sample or identity document that is being submitted.  Note there is no request body information
        to distinguish between the submission of these two types (facial sample vs. ID document).  Algorithm providers must 
        make this distinction using internal logic.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Image'

  responses:
    padAnalysisResponse:
      description: PAD Analysis response object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PADAnalysis'
    400:
      description: The request is malformed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404:
      description: No ongoing transaction was found for the specified StationID.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    410:
      description: The test volunteer has exited the station and the transaction has ended.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    429:
      description: Too many requests for the ongoing transaction.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    500:
      description: This capture failed because of a server side issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
